# Generated by Django 5.2.3 on 2025-06-14 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('pais_id', models.AutoField(primary_key=True, serialize=False)),
                ('pais_nome', models.CharField(default='', max_length=100)),
                ('pais_moeda', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('regiao_id', models.AutoField(primary_key=True, serialize=False)),
                ('regiao_tipo', models.CharField(choices=[('CAP', 'Capital'), ('TUR', 'Turístico'), ('CTR', 'Centro'), ('INT', 'Interior')], max_length=10)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_simu.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('cidade_id', models.AutoField(primary_key=True, serialize=False)),
                ('cidade_nome', models.CharField(default='', max_length=100)),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_simu.regiao')),
            ],
        ),
    ]
